// <auto-generated />
using Agenciaapi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agenciaapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240111012413_primeiramigration")]
    partial class primeiramigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Agenciaapi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cpfCliente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("emailCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("enderecoCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("nomeCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("telefoneCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            cpfCliente = "111.895.787-11",
                            emailCliente = "01@hotmail",
                            enderecoCliente = "bla bla bla",
                            nomeCliente = "Ana",
                            telefoneCliente = "1111"
                        },
                        new
                        {
                            Id = 2,
                            cpfCliente = "222.895.787-11",
                            emailCliente = "02@hotmail",
                            enderecoCliente = "logo ali",
                            nomeCliente = "Joana",
                            telefoneCliente = "2222"
                        },
                        new
                        {
                            Id = 3,
                            cpfCliente = "333.895.787-11",
                            emailCliente = "03@hotmail",
                            enderecoCliente = "bla bla bla",
                            nomeCliente = "Mara",
                            telefoneCliente = "3333"
                        },
                        new
                        {
                            Id = 4,
                            cpfCliente = "444.895.787-11",
                            emailCliente = "04@hotmail",
                            enderecoCliente = "logo ali",
                            nomeCliente = "Anderson",
                            telefoneCliente = "4444"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
